### ISSUE TITLE
Create milestone doc

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/PPL_OutlierPrediction#1]
1. Create a list of milestones.

2.Figure out a home for the list.

Some choices for #2:  

- Use GitHub issues; 
- Use  GitHub Projects;   
- create a ProjectManagement subdir in the repo and make it a text or formatted text file in that dir

-  Use slack
- Create a Projects folder on google drive and organize our docs there.

**Comment by MarlinRLee** [comment]
Tasks:
1.  Implement julia Code for first three section
2. Data Prep 1: detrend and simplify
3. Come up with better priors
4. Communicate results (Plotting, tables?)
5. Data Prep 2: ?
6. Implement section 4 - 10 (2/3 tasks?)
7. Improve model (priors, method?)

**Comment by SteveGoldstein** [comment]
Now that we've seen importance sampling doesn't work out of the box, that suggests a new milestone:   figure out how to get a reasonable answer with importance sampling.
