### ISSUE TITLE
Create Project planning document

### ISSUE THREAD

**Issue by MarlinRLee** [AFIDSI/PPL_OutlierPrediction#2]
Goals:
(Large thing we want to do)
1. See if Gen is a good tool for task
- Gives insight to the nature of the data
- Gives platform to expand analysis 
- Gets better results then current methods
2. Improve Gen understanding

Objectives:
(Things we do to get the goals)
1. Get a model that gives reasonable result
- Align with current models
2. Get a model that is better then current model
- Provide redundant results
- ?
3. Get code that takes inputs and outputs outliers
-( Accepts a file and outputs a dataframe with a column saying if the row is flagged)?
-Get Gen to detrend the data

**Comment by SteveGoldstein** [comment]
Additional goal:   Create a template for spinning up a DSI research team.
Companion objective:  Document key elements of our process as we are creating this research team.
