### ISSUE TITLE
step05 has two jl files

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/PPL_OutlierPrediction#9]
steps 01-04 each have just one stepNN.jl file but step05 has two.  This inconsistency necessitate what seems like avoidable confusion in the condor submit file and shell scripts.   Are both these necessary?  Is there another solution?

**Comment by amegahed** [comment]
I propose that we just move the smooth quadratic model into a new step (step06).

**Comment by SteveGoldstein** [comment]
For the next release...

**Comment by amegahed** [comment]
Since this is a super simple change, I went ahead and moved the quadratic model into step06.   Hope this is ok.   I think it makes the project easier to understand and it follows the approach of  later steps building upon earlier steps.
